pipeline {
	agent any
	stages {
		stage('Create blue kubernetes cluster') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-static') {
					sh '''
						eksctl create cluster \
						--name blue1 \
						--version 1.13 \
						--nodegroup-name blue-standard-workers \
						--node-type t2.small \
						--nodes 3 \
						--nodes-min 1 \
						--nodes-max 4 \
						--node-ami auto
					'''
				}
			}
		}

		stage('Create green kubernetes cluster') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-static') {
					sh '''
						eksctl create cluster \
						--name green2 \
						--version 1.13 \
						--nodegroup-name green-standard-workers \
						--node-type t2.small \
						--nodes 3 \
						--nodes-min 1 \
						--nodes-max 4 \
						--node-ami auto
					'''
				}
			}
		}

		stage('Create configuration blue') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-static') {
					sh '''
						aws eks --region us-west-2 update-kubeconfig --name blue1
					'''
				}
			}
		}

		stage('Create configuration green') {
			steps {
				withAWS(region:'us-west-2', credentials:'aws-static') {
					sh '''
						aws eks --region us-west-2 update-kubeconfig --name green2
					'''
				}
			}
		}
	}
}
